from enum import Enum
from typing import Any, TypeVar, assert_never

from adaptix import Retort

from maxo.bot.methods import (
    AddMembers,
    AnswerOnCallback,
    DeleteAdmin,
    DeleteChat,
    DeleteMessage,
    EditBotInfo,
    EditChat,
    EditMessage,
    EditMyCommands,
    GetAdmins,
    GetChat,
    GetChatByLink,
    GetChats,
    GetMembers,
    GetMembership,
    GetMessageById,
    GetMessages,
    GetMyInfo,
    GetPinnedMessage,
    GetSubscriptions,
    GetUpdates,
    GetUploadUrl,
    GetVideoAttachmentDetails,
    LeaveChat,
    PinMessage,
    PostAdmins,
    RemoveMember,
    SendAction,
    SendMessage,
    SetAdmins,
    Subscribe,
    UnpinMessage,
    Unsubscribe,
    UploadMedia,
)
from maxo.types import (
    Attachment,
    AttachmentPayload,
    AttachmentRequest,
    Attachments,
    AttachmentsRequests,
    AudioAttachment,
    AudioAttachmentRequest,
    BaseMaxoType,
    BaseUpdate,
    BotAddedToChat,
    BotCommand,
    BotCommandsInfo,
    BotInfo,
    BotRemovedFromChat,
    BotStarted,
    BotStopped,
    Button,
    Callback,
    CallbackButton,
    Chat,
    ChatAdmin,
    ChatAdminsList,
    ChatList,
    ChatMember,
    ChatMembersList,
    ChatTitleChanged,
    ClipboardButton,
    ContactAttachment,
    ContactAttachmentPayload,
    ContactAttachmentRequest,
    ContactAttachmentRequestPayload,
    DialogCleared,
    DialogMuted,
    DialogRemoved,
    DialogUnmuted,
    EmphasizedMarkup,
    FailedUserDetails,
    FileAttachment,
    FileAttachmentPayload,
    FileAttachmentRequest,
    GetPinnedMessageResult,
    GetSubscriptionsResult,
    HeadingMarkup,
    HighlightedMarkup,
    Image,
    InlineButtons,
    InlineKeyboardAttachment,
    InlineKeyboardAttachmentRequest,
    InlineKeyboardAttachmentRequestPayload,
    Keyboard,
    LinkButton,
    LinkMarkup,
    LinkedMessage,
    LocationAttachment,
    LocationAttachmentRequest,
    MarkupElement,
    MarkupElements,
    MaxUpdate,
    MaxoType,
    MediaAttachmentPayload,
    MediaAttachments,
    MediaAttachmentsRequests,
    Message,
    MessageBody,
    MessageButton,
    MessageCallback,
    MessageCreated,
    MessageEdited,
    MessageList,
    MessageRemoved,
    MessageStat,
    ModifyMembersResult,
    MonospacedMarkup,
    NewMessageBody,
    NewMessageLink,
    OpenAppButton,
    PhotoAttachment,
    PhotoAttachmentPayload,
    PhotoAttachmentRequest,
    PhotoAttachmentRequestPayload,
    PhotoToken,
    QuoteMarkup,
    Recipient,
    RequestContactButton,
    RequestGeoLocationButton,
    SendMessageResult,
    ShareAttachment,
    ShareAttachmentPayload,
    ShareAttachmentRequest,
    SimpleQueryResult,
    StickerAttachment,
    StickerAttachmentPayload,
    StickerAttachmentRequest,
    StickerAttachmentRequestPayload,
    StrikethroughMarkup,
    StrongMarkup,
    Subscription,
    UnderlineMarkup,
    UpdateContext,
    UpdateList,
    Updates,
    UploadEndpoint,
    UploadMediaResult,
    UploadedInfo,
    User,
    UserAddedToChat,
    UserMentionMarkup,
    UserRemovedFromChat,
    UserWithPhoto,
    VideoAttachment,
    VideoAttachmentDetails,
    VideoAttachmentRequest,
    VideoThumbnail,
    VideoUrls,
)


class WarmingUpType(Enum):
    METHOD = "method"
    TYPES = "types"


_types = (
    Attachment,
    AttachmentPayload,
    AttachmentRequest,
    Attachments,
    AttachmentsRequests,
    AudioAttachment,
    AudioAttachmentRequest,
    BaseMaxoType,
    BaseUpdate,
    BotAddedToChat,
    BotCommand,
    BotCommandsInfo,
    BotInfo,
    BotRemovedFromChat,
    BotStarted,
    BotStopped,
    Button,
    Callback,
    CallbackButton,
    Chat,
    ChatAdmin,
    ChatAdminsList,
    ChatList,
    ChatMember,
    ChatMembersList,
    ChatTitleChanged,
    ClipboardButton,
    ContactAttachment,
    ContactAttachmentPayload,
    ContactAttachmentRequest,
    ContactAttachmentRequestPayload,
    DialogCleared,
    DialogMuted,
    DialogRemoved,
    DialogUnmuted,
    EmphasizedMarkup,
    FailedUserDetails,
    FileAttachment,
    FileAttachmentPayload,
    FileAttachmentRequest,
    GetPinnedMessageResult,
    GetSubscriptionsResult,
    HeadingMarkup,
    HighlightedMarkup,
    Image,
    InlineButtons,
    InlineKeyboardAttachment,
    InlineKeyboardAttachmentRequest,
    InlineKeyboardAttachmentRequestPayload,
    Keyboard,
    LinkButton,
    LinkMarkup,
    LinkedMessage,
    LocationAttachment,
    LocationAttachmentRequest,
    MarkupElement,
    MarkupElements,
    MaxUpdate,
    MaxoType,
    MediaAttachmentPayload,
    MediaAttachments,
    MediaAttachmentsRequests,
    Message,
    MessageBody,
    MessageButton,
    MessageCallback,
    MessageCreated,
    MessageEdited,
    MessageList,
    MessageRemoved,
    MessageStat,
    ModifyMembersResult,
    MonospacedMarkup,
    NewMessageBody,
    NewMessageLink,
    OpenAppButton,
    PhotoAttachment,
    PhotoAttachmentPayload,
    PhotoAttachmentRequest,
    PhotoAttachmentRequestPayload,
    PhotoToken,
    QuoteMarkup,
    Recipient,
    RequestContactButton,
    RequestGeoLocationButton,
    SendMessageResult,
    ShareAttachment,
    ShareAttachmentPayload,
    ShareAttachmentRequest,
    SimpleQueryResult,
    StickerAttachment,
    StickerAttachmentPayload,
    StickerAttachmentRequest,
    StickerAttachmentRequestPayload,
    StrikethroughMarkup,
    StrongMarkup,
    Subscription,
    UnderlineMarkup,
    UpdateContext,
    UpdateList,
    Updates,
    UploadEndpoint,
    UploadMediaResult,
    UploadedInfo,
    User,
    UserAddedToChat,
    UserMentionMarkup,
    UserRemovedFromChat,
    UserWithPhoto,
    VideoAttachment,
    VideoAttachmentDetails,
    VideoAttachmentRequest,
    VideoThumbnail,
    VideoUrls,
)


_methods = (
    AddMembers,
    AnswerOnCallback,
    DeleteAdmin,
    DeleteChat,
    DeleteMessage,
    EditBotInfo,
    EditChat,
    EditMessage,
    EditMyCommands,
    GetAdmins,
    GetChat,
    GetChatByLink,
    GetChats,
    GetMembers,
    GetMembership,
    GetMessageById,
    GetMessages,
    GetMyInfo,
    GetPinnedMessage,
    GetSubscriptions,
    GetUpdates,
    GetUploadUrl,
    GetVideoAttachmentDetails,
    LeaveChat,
    PinMessage,
    PostAdmins,
    RemoveMember,
    SendAction,
    SendMessage,
    SetAdmins,
    Subscribe,
    UnpinMessage,
    Unsubscribe,
    UploadMedia,
)

_RetortT = TypeVar("_RetortT", bound=Retort)


def warming_up_retort(
    retort: _RetortT,
    warming_up: WarmingUpType | None = None,
) -> _RetortT:
    if warming_up is None:
        return retort

    types: tuple[Any, ...]
    if warming_up is WarmingUpType.METHOD:
        types = _methods
        retort_method = retort.get_dumper
    elif warming_up is WarmingUpType.TYPES:
        types = _types
        retort_method = retort.get_loader
    else:
        assert_never(warming_up)

    for tp in types:
        retort_method(tp)  # type: ignore[arg-type]

    return retort
